### ISSUE TITLE
Remove "forked from" information.

### ISSUE THREAD

**Issue by prmtl** [osm-pl/osm24#14]
Hi!

I've asked GitHub support to convert this repo from "fork" to "normal". This would enable things like code searching, default target for pull requests etc.
They need someone with admin permission to contact them through https://support.github.com/contact and confirm that (@kocio-pl?).  My message looked like that (feel free to copy):
```
Hi!

I would like to remove "forked from dotevo/osm24" information from repository "osm-pl/osm24".
The reason is that "osm-pl/osm24" is the main place where development ("dotevo/osm24" is no longer maintainer) is taking place and it might confuse people wanting to make contributions or looking for help. "dotevo/osm24" was forked into "osm-pl/osm24" instead of transferred by the original author probably by mistake.

Best,
Sebastian
```

Of course information about original author will not be removed and we can add link in README to original repo.

**Comment by kocio-pl** [comment]
I'm not sure who do they mean - the owner of osm-pl (@Teiron) maybe?

**Comment by Teiron** [comment]
I can try doing that.

**Comment by kocio-pl** [comment]
@Teiron Great, thanks! 

BTW it would be safer if there was at least some backup for admin functions for osm-pl (see https://github.com/orgs/osm-pl/people ), there are usually problems with single people in charge, sometimes after years of operations (for example case of OSM forum). What do you think about it?

**Comment by Teiron** [comment]
Would you like to share this post with me?

**Comment by kocio-pl** [comment]
I'm confused - which post do you mean?

**Comment by Teiron** [comment]
Post as in position

**Comment by kocio-pl** [comment]
Yes, please.

**Comment by kocio-pl** [comment]
Thanks to @Teiron I have now "Owner" role in osm-pl, so I sent the confirmation.

**Comment by kocio-pl** [comment]
It's done now.
